apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: marketplace-tools
  annotations:
    autogenSpecType: SINGLE_VM
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Google Cloud Marketplace Terraform Module
    version: v1.3.1725480158
    actuationTool:
      flavor: Terraform
      version: ">= 1.2"
    description: {}
    softwareGroups:
      - type: SG_OS
        software:
          - title: jetOS
            version: "v1.3"
  content: {}
  interfaces:
    variables:
      - name: project_id
        description: The ID of the project in which to provision resources.
        varType: string
        required: true
      - name: ssh_pub_key_file
        description: The path to the public SSH key to provide to the VM instance.
        varType: string
        defaultValue: create
      - name: goog_cm_deployment_name
        description: The name of the deployment and VM instance.
        varType: string
        required: true
      - name: source_image
        description: The image name for the disk for the VM instance.
        varType: string
        defaultValue: projects/jet-technology-labs-public/global/images/sk-vpn-prod-v1-3-1725480158
      - name: zone
        description: The zone for the solution to be deployed.
        varType: string
        defaultValue: us-west1-b
      - name: boot_disk_type
        description: The boot disk type for the VM instance.
        varType: string
        defaultValue: pd-standard
      - name: boot_disk_size
        description: The boot disk size for the VM instance in GBs
        varType: integer
        defaultValue: 10
      - name: machine_type
        description: The machine type to create, e.g. e2-small
        varType: string
        defaultValue: c2-standard-8
      - name: networks
        description: The network name to attach the VM instance.
        varType: list(string)
        defaultValue: ["mgmt", "wan", "lan"]
      - name: sub_networks
        description: The sub network name to attach the VM instance.
        varType: list(string)
        defaultValue: ["mgmt-subnet", "wan-subnet", "lan-subnet"]
      - name: external_ips
        description: The external IPs assigned to the VM for public access.
        varType: list(string)
        defaultValue: ["mgmt-public-ip","wan-public-ip","NONE"]
      - name: enable_tcp_22
        description: Allow TCP port 22 traffic from the Internet
        varType: bool
        defaultValue: true
      - name: tcp_22_source_ranges
        description: Source IP ranges for TCP port 22 traffic
        varType: string
        defaultValue: ""
      - name: enable_tcp_443
        description: Allow HTTPS traffic from the Internet
        varType: bool
        defaultValue: true
      - name: tcp_443_source_ranges
        description: Source IP ranges for HTTPS traffic
        varType: string
        defaultValue: ""
      - name: ip_forward
        description: Whether to allow sending and receiving of packets with non-matching source or destination IPs.
        varType: bool
        defaultValue: true
      - name: enable_cloud_logging
        description: Enables Cloud Logging.
        varType: bool
        defaultValue: true
      - name: enable_cloud_monitoring
        description: Enables Cloud Monitoring.
        varType: bool
        defaultValue: true
    outputs:
      - name: instance_machine_type
        description: Machine type for the compute instance.
      - name: mgmt_nat_ip
        description: External IP of the MGMT interface.
      - name: wan_nat_ip
        description: External IP of the WAN interface.
      - name: mgmt_network
        description: Self-link for the network of the compute instance.
      - name: instance_self_link
        description: Self-link for the compute instance.
      - name: instance_zone
        description: Zone for the compute instance.
      - name: admin_url
        description: Admin Url
      - name: ssh_key
        description: SSH Private Key       
